version: "2"
plugins:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize.xml"
  duplication:
    enabled: true
    config:
      languages:
        - php
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.xml"
      file_extensions: "php"
exclude_patterns:
  - "tests/"
  - "**.md"
  - "**.json"
  - "**.xml"
  - config/**/*
  - tests/**/*
  - public/js/*
