version: "2"
plugins:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize.xml"
  duplication:
    enabled: true
    config:
      languages:
        - php
        - javascript
    exclude_fingerprints:
      - 833a4a37e3112811e59a5b092e63996f
      - d90920269fa34d35432b628f9743662f
      - 5547d17547861d344eccea6fcadcb06e
      - 6f2d47f9dfa927ed087783607b2733c3
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR2"
      file_extensions: "php"
    checks:
      Generic Files LineLength TooLong:
        enabled:false
exclude_patterns:
  - "tests/"
  - "**.md"
  - "**.json"
  - "**.xml"
  - config/**/*
  - tests/**/*
  - public/js/*
